
import {Product} from './types';
export const products:Product[]=[
    {
        id:1,
        title:"Gray Top",
        img:"/pictures/bestSelling.jpg",
        slug:"gray-top",
        price:1234,
        category:"top",
        description:"Most Elegant and decent Gray Top",
        size:["S","MD","L","XL","XXL"],
        color:["#ffffff","#000000","#e60000"],
        qty:1,
        discount:0,
    },
    {
        id:2,
        title:"Red High Neck",
        img:"/pictures/bestSelling3.jpg",
        slug:"red-high-neck",
        price:1234,
        category:"top",
        description:"Most Elegant and decent Red High Neck",
        size:["S","MD","L","XL","XXL"],
        color:["#ffffff","#000000","#e60000"],
        qty:1,
        discount:0,
    },
    {
        id:3,
        title:"Blue Top with Pants",
        img:"/pictures/bestSelling3.jpg",
        slug:"blue-top-with-pants",
        price:1234,
        category:"top",
        description:"Most Elegant and decent Blue Top with Pants",
        size:["S","MD","L","XL","XXL"],
        color:["#ffffff","#000000","#e60000"],
        qty:1,
        discount:0,
    },
    {
        id:4,
        title:"White Top",
        img:"/pictures/bestSelling5.jpg",
        slug:"white-top",
        price:1234,
        category:"top",
        description:"Most Elegant and decent white top",
        size:["S","MD","L","XL","XXL"],
        color:["#ffffff","#000000","#e60000"],
        qty:1,
        discount:0,
    },
    {
        id:5,
        title:"Half White Top",
        img:"/pictures/bestSelling6.jpg",
        slug:"half-white-top",
        price:1234,
        category:"top",
        description:"Most Elegant and decent Half White Top",
        size:["S","MD","L","XL","XXL"],
        color:["#ffffff","#000000","#e60000"],
        qty:1,
        discount:0,
    },
    {
        id:6,
        title:"Blue Overcoat",
        img:"/pictures/bestSelling7.jpg",
        slug:"blue-overcoat",
        price:1234,
        category:"top",
        description:"Most Elegant and decent Blue Overcoat",
        size:["S","MD","L","XL","XXL"],
        color:["#ffffff","#000000","#e60000"],
        qty:1,
        discount:0,
    },
    {
        id:7,
        title:"Black Overcoat",
        img:"/pictures/bestSelling9.jpg",
        slug:"black-overcoat",
        price:1234,
        category:"top",
        description:"Most Elegant and decent Black Overcoat",
        size:["S","MD","L","XL","XXL"],
        color:["#ffffff","#000000","#e60000"],
        qty:1,
        discount:0,
    },

];

